# Generated by Django 5.2.5 on 2025-09-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip'),
    ]

    operations = [
    ]
