# Generated by Django 5.2.5 on 2025-09-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_auto_20250902_1746'),
        ('ip_tracking', '0003_auto_add_country_city'),
    ]

    operations = [
    ]
